FROM postgres:14.3
RUN apt-get update && apt-get install postgis -y
RUN apt-get update && apt-get install postgresql-14-postgis-3 -y
RUN apt-get update && apt-get install postgresql-14-postgis-3-scripts -y
